; Generic OPC Server Parameter File
; Rössel, Siemens AG
; July, 2003


[Registry]
ProgId		= OPC.SinumerikEvents
ClassId		= {1CFE06B9-9DB1-11d3-AD5D-00609792C572}
		  
SymbolicName	= OPC.SinumerikEvents

RegKey		= SinumerikEvents
;needed to access configuration information at runtime


[Configuration]
VendorInfo	= SINUMERIK OPC-Server Alarm&Event-V3.3.0.41  (C) Siemens AG (1999-2003)

IEventServer	= @SinHMIEventSvr.EventSvrObj
