; SINUMERIK OPC Server Parameter File
; Juni 2003
;

[Registry]
ProgId		= OPC.SINUMERIK.Machineswitch
ClassId		= {75d00afe-dda5-11d1-b944-9e614d000000}
SymbolicName	= OPC.SINUMERIK.Machineswitch

RegKey		= SINUMERIK.Machineswitch
;needed to access configuration information at runtime

[Configuration]
VendorInfo	= SINUMERIK OPC-Server DataAccess-V2.4.2.98  (C) Siemens AG (1998-2003)

NoAccessPath	= 1

IVarServer	= @MCVar.Var2
;INSInfoServer	= 
