[Folders]
;Ricostruisco le cartelle standard del sever OPC UA Standard (non Legacy) di siemens
FLD1=name:="Random",parent:="ROOT"
FLD11=name:="PLC",parent:="FLD1"
FLD2=name:="Channel",parent:="ROOT"
FLD21=name:="State",parent:="FLD2"
FLD22=name:="ProgramInfo",parent:="FLD2"
FLD3=name:="Bag",parent:="ROOT"
FLD31=name:="State",parent:="FLD3"
FLD4=name:="Hmi",parent:="ROOT"

[Variables]
;Usata con OPC UA Standard
VAR1=name:="opMode",parent:="FLD31",type:="String",path:="/BAG/State/opmode"
VAR2=name:="progStatus",parent:="FLD21",type:="UInt16",path:="/Channel/State/progStatus"
VAR3=name:="actTNumber",parent:="FLD21",type:="Int",path:="/Channel/State/actTNumber"
VAR4=name:="actToolIdent",parent:="FLD21",type:="String",path:="/Channel/State/actToolIdent"
VAR5=name:="PartProgramName",parent:="FLD22",type:="String",path:="/Channel/ProgramInfo/workPandProgName[u1]"
VAR6=name:="workPandProgName[u1]",parent:="FLD22",type:="String",path:="/Channel/ProgramInfo/workPandProgName[u1]"
VAR7=name:="workPandProgName[u2]",parent:="FLD22",type:="String",path:="/Channel/ProgramInfo/workPandProgName[u2]"

;PLC-Variablen, Bsp. für jeden Datentyp
;PLC-Variables, examples for every datatype 
;VAR30=name:="TestBool",parent:="FLD2",type:="Bool",path:="DB103.DBX6.0",readonly:="false"
;VAR31=name:="TestByte",parent:="FLD2",type:="Byte",path:="DB103.DBB8",readonly:="false"
;VAR32=name:="TestWord",parent:="FLD2",type:="Word",path:="DB103.DBW10",readonly:="false"
;VAR33=name:="TestInt",parent:="FLD2",type:="Int",path:="DB103.DBW12:INT",readonly:="false"
;VAR34=name:="TestInt_Readonly",parent:="FLD2",type:="Int",path:="DB103.DBW12:INT"
;VAR35=name:="TestDWord",parent:="FLD2",type:="DWord",path:="DB103.DBD18",readonly:="false"
;VAR36=name:="TestDInt",parent:="FLD2",type:="DInt",path:="DB103.DBD22:DINT",readonly:="false"
;VAR37=name:="TestDouble",parent:="FLD2",type:="Double",path:="DB103.DBD26:REAL",readonly:="false"
;VAR38=name:="TestFloat",parent:="FLD2",type:="Float",path:="DB103.DBD26:REAL",readonly:="false"

;Alarm variables 
; by default only the topmost  Alarm is available in the Variable "SinumerikAlarm1"
;if you want to get the 10 topmost alarms change the Entry "NumOpcUaAlarms" to 10 in the file "runopcua.ini"
VAR70=name:="OpcUaAlarm1",parent:="FLD4",type:="String",path:="/Hmi/OpcUaAlarm1"
VAR80=name:="OpcUaAlarmNumbers",parent:="FLD4",type:="String",path:="/Hmi/OpcUaAlarmNumbers"

